pipeline {
    agent any
    
    stages {
        stage('Get from SCM') {
            steps {
                git 'https://github.com/DilshanMadhusanka/3960---Herath-HMDM'
            }
        }
        
        stage('Dockerize the application') {
            steps {
                sh 'sudo docker build -t Restaurant-Landing-Page .'
            }
        }
        
        stage('Containerize the application') {
            steps {
                sh 'sudo docker run -d  -p 3000:3000 Restaurant-Landing-Page'
            }
        }
    }
}